name: fluffyhelpers_meditation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.2.0
  shared_preferences: ^2.3.4
  path_provider: ^2.0.12
  json_annotation: ^4.8.0
  just_audio: ^0.9.20
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  firebase_ui_auth: ^1.16.1
  flutter_inappwebview: ^6.1.5
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.4.6
  settings_ui: ^2.0.2
  url_launcher: ^6.3.1
  supabase_flutter: ^2.9.0
  file_picker: ^10.1.9
  path: ^1.9.1
  flutter_translate: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
   - family: Comfortaa
     fonts:
      - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
        weight: 700
      - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
        weight: 500
      - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
        weight: 400
      - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
        weight: 200

  assets:
    - assets/images/
    - assets/images/subcategories_backgrounds/
    - assets/music/
    - assets/users/users.json
    - dotenv

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/icon.png"

flutter_native_splash:
  color: "#001E38"
  color_dark: "##001E38"

  android_12:
    image: assets/images/icon_splash.png
    image_dark: assets/images/icon_splash.png

